export const CREATE_SUPERHERO = "CREATE_SUPERHERO";
export const RETRIEVE_FAV_SUPERHEROS = "RETRIEVE_FAV_SUPERHEROS";
export const UPDATE_SUPERHERO = "UPDATE_SUPERHERO";
export const DELETE_SUPERHERO = "DELETE_SUPERHERO";
